"""comment_reply

Revision ID: 127a143ce65d
Revises: 2d2ab52172ab
Create Date: 2025-07-15 14:41:30.313772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127a143ce65d'
down_revision: Union[str, Sequence[str], None] = '2d2ab52172ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_auto_reply_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('instagram_user_id', sa.String(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_auto_reply_log_comment_id'), 'instagram_auto_reply_log', ['comment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_auto_reply_log_comment_id'), table_name='instagram_auto_reply_log')
    op.drop_table('instagram_auto_reply_log')
    # ### end Alembic commands ###
