"""Add DM auto reply status table

Revision ID: 76b184bd5425
Revises: f123456789ac
Create Date: 2025-07-14 11:51:16.645893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b184bd5425'
down_revision: Union[str, Sequence[str], None] = 'f123456789ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_auto_reply_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_user_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_processed_dm_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_auto_reply_status_id'), 'dm_auto_reply_status', ['id'], unique=False)
    op.create_index(op.f('ix_dm_auto_reply_status_instagram_user_id'), 'dm_auto_reply_status', ['instagram_user_id'], unique=True)
    op.create_table('global_auto_reply_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_user_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_auto_reply_status_id'), 'global_auto_reply_status', ['id'], unique=False)
    op.create_index(op.f('ix_global_auto_reply_status_instagram_user_id'), 'global_auto_reply_status', ['instagram_user_id'], unique=True)
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('post_type', sa.Enum('PHOTO', 'CAROUSEL', 'REEL', name='posttype_new'), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_time', sa.String(length=5), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='frequencytype'), nullable=False),
    sa.Column('scheduled_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_id'), 'scheduled_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_posts_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index(op.f('ix_global_auto_reply_status_instagram_user_id'), table_name='global_auto_reply_status')
    op.drop_index(op.f('ix_global_auto_reply_status_id'), table_name='global_auto_reply_status')
    op.drop_table('global_auto_reply_status')
    op.drop_index(op.f('ix_dm_auto_reply_status_instagram_user_id'), table_name='dm_auto_reply_status')
    op.drop_index(op.f('ix_dm_auto_reply_status_id'), table_name='dm_auto_reply_status')
    op.drop_table('dm_auto_reply_status')
    # ### end Alembic commands ###
