"""Add bulk_composer_content table

Revision ID: d123456789ef
Revises: c123456789cd
Create Date: 2024-01-08 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd123456789ef'
down_revision = 'a27f455d018a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_composer_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('media_file', sa.Text(), nullable=True),
    sa.Column('media_filename', sa.String(length=255), nullable=True),
    sa.Column('media_generated', sa.Boolean(), nullable=True),
    sa.Column('scheduled_date', sa.String(length=10), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('scheduled_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('facebook_post_id', sa.String(length=255), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=True),
    sa.Column('last_publish_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_composer_content_id'), 'bulk_composer_content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulk_composer_content_id'), table_name='bulk_composer_content')
    op.drop_table('bulk_composer_content')
    # ### end Alembic commands ### 