"""schedule updated

Revision ID: e760799b04f2
Revises: 76b184bd5425
Create Date: 2025-07-15 09:44:05.223468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e760799b04f2'
down_revision: Union[str, Sequence[str], None] = '76b184bd5425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('time_slot', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scheduled_posts', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scheduled_posts', 'strategy_plans', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_posts', type_='foreignkey')
    op.drop_column('scheduled_posts', 'strategy_id')
    op.drop_table('strategy_plans')
    # ### end Alembic commands ###
